export const ALGERIA_LOCATIONS: Record<string, string[]> = {
    "Adrar": [
        "Adrar",
        "Akabli",
        "Aougrout",
        "Aoulef",
        "Bordj Badji Mokhtar",
        "Bouda",
        "Charouine",
        "Deldoul",
        "Fenoughil",
        "In Zghmir",
        "Ksar Kaddour",
        "Metarfa",
        "Ouled Ahmed Tammi",
        "Ouled Aissa",
        "Ouled Said",
        "Reggane",
        "Sali",
        "Sbaa",
        "Talmine",
        "Tamentit",
        "Tamest",
        "Timiaouine",
        "Timimoun",
        "Timokten",
        "Tinerkouk",
        "Tit",
        "Tsabit",
        "Zaouiet Kounta"
    ],
    "Chlef": [
        "Abou El Hassen",
        "Ain Merane",
        "Benairia",
        "Beni Bouateb",
        "Beni Haoua",
        "Beni Rached",
        "Boukadir",
        "Bouzghaia",
        "Breira",
        "Chettia",
        "Chlef",
        "Dahra",
        "El Hadjadj",
        "El Karimia",
        "El Marsa",
        "Harchoun",
        "Herenfa",
        "Labiod Medjadja",
        "Moussadek",
        "Oued Fodda",
        "Oued Goussine",
        "Oued Sly",
        "Ouled Abbes",
        "Ouled Ben Abdelkader",
        "Ouled Fares",
        "Oum Drou",
        "Sendjas",
        "Sidi Abderrahmane",
        "Sidi Akacha",
        "Sobha",
        "Tadjna",
        "Talassa",
        "Taougrite",
        "Tenes",
        "Zeboudja"
    ],
    "Laghouat": [
        "Ain Mahdi",
        "Ain Sidi Ali",
        "Beidha",
        "Benacer Ben Chohra",
        "Brida",
        "El Assafia",
        "El Ghicha",
        "El Haouaita",
        "El Kheneg",
        "Gueltat Sidi Saad",
        "Hadj Mechri",
        "Hassi Delaa",
        "Hassi R'Mel",
        "Ksar El Hirane",
        "Laghouat",
        "Oued M'Zi",
        "Oued Morra",
        "Sebgag",
        "Sidi Bouzid",
        "Sidi Makhlouf",
        "Tadjmout",
        "Tadjrouna",
        "Taouiala"
    ],
    "Oum El Bouaghi": [
        "Ain Babouche",
        "Ain Beida",
        "Ain Diss",
        "Ain Fekroune",
        "Ain Kercha",
        "Ain M'lila",
        "Ain Zitoun",
        "Behir Chergui",
        "Berriche",
        "Bir Chouhada",
        "Dhala",
        "El Amiria",
        "El Belala",
        "El Djazia",
        "El Fedjoudj Boughrara Saoudi",
        "El Harmilia",
        "Fkirina",
        "Hanchir Toumghani",
        "Ksar Sbahi",
        "Meskiana",
        "Oued Nini",
        "Ouled Gacem",
        "Ouled Hamla",
        "Ouled Zouai",
        "Oum El Bouaghi",
        "Rahia",
        "Sigus",
        "Souk Naamane",
        "Zorg"
    ],
    "Batna": [
        "Ain Djasser",
        "Ain Touta",
        "Ain Yagout",
        "Arris",
        "Batna",
        "Beni Foudhala El Hakania",
        "Boulhilat",
        "Boumagueur",
        "Boumia",
        "Bouzina",
        "Chemora",
        "Chir",
        "Djerma",
        "El Hassi",
        "El Madher",
        "Fesdis",
        "Foum Toub",
        "Ghassira",
        "Gosbat",
        "Guigba",
        "Hidoussa",
        "Ichmoul",
        "Inoughissen",
        "Kimmel",
        "Ksar Belezma",
        "Larbaa",
        "Lazrou",
        "Lemsane",
        "Maafa",
        "Menaa",
        "Merouana",
        "Ngaous",
        "Oued Chaaba",
        "Oued El Ma",
        "Oued Taga",
        "Ouled Aouf",
        "Ouled Fadel",
        "Ouled Selam",
        "Ouled Si Slimane",
        "Ouyoun El Assafir",
        "Rahbat",
        "Ras El Aioun",
        "Sefiane",
        "Seriana",
        "Talkhamt",
        "Taxlent",
        "Tazoult",
        "Teniet El Abed",
        "Tighanimine",
        "Tigherghar",
        "Timgad",
        "Tkout",
        "Zanat El Beida"
    ],
    "Béjaïa": [
        "Adekar",
        "Ait Djellil",
        "Ait R'zine",
        "Ait Smail",
        "Akbou",
        "Akfadou",
        "Amalou",
        "Amizour",
        "Aokas",
        "Barbacha",
        "Bejaia",
        "Beni Ksila",
        "Beni Maouch",
        "Beni Melikeche",
        "Boudjellil",
        "Bouhamza",
        "Boukhelifa",
        "Chelata",
        "Chemini",
        "Darguina",
        "Draa Kaid",
        "El Kseur",
        "Ferraoun",
        "Ifelain Ilmathen",
        "Ighil Ali",
        "Ighram",
        "Kendira",
        "Kherrata",
        "Leflaye",
        "M'cisna",
        "Melbou",
        "Oued Ghir",
        "Ouzallaguen",
        "Seddouk",
        "Semaoun",
        "Sidi Aich",
        "Sidi Ayad",
        "Souk El Thenine",
        "Souk Oufella",
        "Tala Hamza",
        "Tamokra",
        "Tamridjet",
        "Taourirt Ighil",
        "Taskriout",
        "Tazmalt",
        "Thinabdher",
        "Tibane",
        "Tichi",
        "Tifra",
        "Timzrit",
        "Tizi N'berber",
        "Toudja"
    ],
    "Biskra": [
        "Ain Naga",
        "Besbes",
        "Biskra",
        "Bordj Ben Azzouz",
        "Bouchagroun",
        "Chetma",
        "Doucen",
        "Ech Chaiba",
        "El Feidh",
        "El Ghrous",
        "El Hadjab",
        "El Haouch",
        "Foughala",
        "Khanguet Sidinadji",
        "Lichana",
        "Lioua",
        "M'lili",
        "M'ziraa",
        "Mchouneche",
        "Mekhadma",
        "Ouled Djellal",
        "Oumache",
        "Ourlal",
        "Ras El Miaad",
        "Sidi Khaled",
        "Sidi Okba",
        "Tolga",
        "Zeribet El Oued"
    ],
    "Bechar": [
        "Abadla",
        "Bechar",
        "Beni Abbes",
        "Beni Ikhlef",
        "Beni Ounif",
        "Boukais",
        "El Ouata",
        "Erg Ferradj",
        "Igli",
        "Kenedsa",
        "Kerzaz",
        "Ksabi",
        "Lahmar",
        "Mechraa Houari Boumedienne",
        "Meridja",
        "Mogheul",
        "Ouled Khoudir",
        "Tabalbala",
        "Taghit",
        "Tamtert",
        "Timoudi"
    ],
    "Blida": [
        "Ain Romana",
        "Ben Khlil",
        "Beni Mered",
        "Beni Tamou",
        "Blida",
        "Bouarfa",
        "Boufarik",
        "Bouinan",
        "Chebli",
        "Chiffa",
        "Chrea",
        "Djebabra",
        "El Affroun",
        "Guerrouaou",
        "Hammam Melouane",
        "Larbaa",
        "Meftah",
        "Mouzaia",
        "Oued Djer",
        "Oued El Alleug",
        "Ouled Selama",
        "Ouled Yaich",
        "Souhane",
        "Soumaa"
    ],
    "Bouira": [
        "Aghbalou",
        "Ahl El Ksar",
        "Ain Bessam",
        "Ain El Hadjar",
        "Ain Laloui",
        "Ain Turk",
        "Ait Laaziz",
        "Aomar",
        "Ath Mansour",
        "Bechloul",
        "Bir Ghbalou",
        "Bordj Oukhriss",
        "Bouderbala",
        "Bouira",
        "Boukram",
        "Chorfa",
        "Dechmia",
        "Dirah",
        "Djebahia",
        "El Adjiba",
        "El Asnam",
        "El Hachimia",
        "El Hakimia",
        "El Khebouzia",
        "El Mokrani",
        "Guerrouma",
        "Hadjera Zerga",
        "Haizer",
        "Hanif",
        "Kadiria",
        "Lakhdaria",
        "Maala",
        "Maamora",
        "Mchedallah",
        "Mezdour",
        "Oued El Berdi",
        "Ouled Rached",
        "Raouraoua",
        "Ridane",
        "Saharidj",
        "Souk El Khemis",
        "Sour El Ghozlane",
        "Taghzout",
        "Taguedit",
        "Zbarbar"
    ],
    "Tamanrasset": [
        "Abalessa",
        "Foggaret Ezzaouia",
        "Idles",
        "In Amguel",
        "In Ghar",
        "In Guezzam",
        "In Salah",
        "Tamanghasset",
        "Tazouk",
        "Tinzaouatine"
    ],
    "Tbessa": [
        "Ain Zerga",
        "Bedjene",
        "Bekkaria",
        "Bir Dheb",
        "Bir El Mokadem",
        "Boukhadra",
        "Boulhaf Dyr",
        "Cheria",
        "El Aouinet",
        "El Kouif",
        "El Ma El Biodh",
        "El Mazeraa",
        "El Meridj",
        "El Ogla",
        "Gorriguer",
        "Hammamet",
        "Lahouidjbet",
        "Morsott",
        "Ouenza",
        "Oum Ali",
        "Safsaf El Ouesra",
        "Stah Guentis",
        "Tebessa",
        "Tlidjene"
    ],
    "Tlemcen": [
        "Ain Fetah",
        "Ain Fezza",
        "Ain Ghoraba",
        "Ain Kebira",
        "Ain Nehala",
        "Ain Tallout",
        "Ain Youcef",
        "Amieur",
        "Azails",
        "Bab El Assa",
        "Beni Bahdel",
        "Beni Boussaid",
        "Beni Mester",
        "Beni Ouarsous",
        "Beni Semiel",
        "Beni Snous",
        "Bensekrane",
        "Bouhlou",
        "Chetouane",
        "Dar Yaghmouracene",
        "Djebala",
        "El Fehoul",
        "Fellaoucene",
        "Ghazaouet",
        "Hammam Boughrara",
        "Hennaya",
        "Honaine",
        "Maghnia",
        "Mansourah",
        "Marsa Ben Mhidi",
        "Msirda Fouaga",
        "Nedroma",
        "Oued Chouly",
        "Ouled Mimoun",
        "Ouled Riyah",
        "Remchi",
        "Sabra",
        "Sebbaa Chioukh",
        "Sebdou",
        "Sidi Abdelli",
        "Sidi Medjahed",
        "Souahlia",
        "Souani",
        "Souk El Khemis",
        "Souk Thlata",
        "Terni Beni Hediel",
        "Tianet",
        "Tlemcen",
        "Zenata"
    ],
    "Tiaret": [
        "Ain Bouchekif",
        "Ain Deheb",
        "Ain El Hadid",
        "Ain Kermes",
        "Ain Zarit",
        "Chehaima",
        "Dahmouni",
        "Djillali Ben Amar",
        "Faidja",
        "Frenda",
        "Guertoufa",
        "Madna",
        "Mahdia",
        "Mechraa Safa",
        "Medrissa",
        "Medroussa",
        "Meghila",
        "Mellakou",
        "Nadorah",
        "Naima",
        "Oued Lilli",
        "Ouled Djerad",
        "Rahouia",
        "Sebaine",
        "Sebt",
        "Sidi Abdelghani",
        "Sidi Abderrahmane",
        "Sidi Ali Mellal",
        "Sidi Bakhti",
        "Sidi Hosni",
        "Sougueur",
        "Tagdemt",
        "Takhemaret",
        "Tiaret",
        "Tidda",
        "Tousnina"
    ],
    "Tizi Ouzou": [
        "Abi Youcef",
        "Aghrib",
        "Agouni Gueghrane",
        "Ain El Hammam",
        "Ain Zaouia",
        "Ait Aggouacha",
        "Ait Aissa Mimoun",
        "Ait Bouadou",
        "Ait Boumehdi",
        "Ait Chaffaa",
        "Ait Khelil",
        "Ait Mahmoud",
        "Ait Oumalou",
        "Ait Toudert",
        "Ait Yahia",
        "Ait Yahia Moussa",
        "Akbil",
        "Akerrou",
        "Assi Youcef",
        "Azazga",
        "Azzefoun",
        "Beni Aissi",
        "Beni Douala",
        "Beni Yenni",
        "Beni Ziki",
        "Beni Zmenzer",
        "Boghni",
        "Boudjima",
        "Bounouh",
        "Bouzguen",
        "Draa Ben Khedda",
        "Draa El Mizan",
        "Freha",
        "Frikat",
        "Iboudraren",
        "Idjeur",
        "Iferhounene",
        "Ifigha",
        "Iflissen",
        "Illilten",
        "Iloula Oumalou",
        "Imsouhal",
        "Irdjen",
        "Larba Nait Irathen",
        "Maatka",
        "Makouda",
        "Mechtrass",
        "Mekla",
        "Mizrana",
        "Mkira",
        "Ouacif",
        "Ouadhia",
        "Ouaguenoun",
        "Sidi Naamane",
        "Souamaa",
        "Souk El Thenine",
        "Tadmait",
        "Tigzirt",
        "Timizart",
        "Tirmitine",
        "Tizi Ghenif",
        "Tizi Nthlata",
        "Tizi Ouzou",
        "Tizi Rached",
        "Yakouren",
        "Yatafen",
        "Zekri"
    ],
    "Alger": [
        "Ain Benian",
        "Ain Taya",
        "Alger Centre",
        "Bab Azzouar",
        "Bab El Oued",
        "Baba Hassen",
        "Bachedjerah",
        "Baraki",
        "Belouizdad",
        "Ben Aknoun",
        "Beni Messous",
        "Bir Mourad Rais",
        "Birkhadem",
        "Birtouta",
        "Bologhine",
        "Bordj El Bahri",
        "Bordj El Kiffan",
        "Bourouba",
        "Bouzareah",
        "Casbah",
        "Cheraga",
        "Dar El Beida",
        "Dely Ibrahim",
        "Djasr Kasentina",
        "Douera",
        "Draria",
        "El Achour",
        "El Biar",
        "El Hammamet",
        "El Harrach",
        "El Madania",
        "El Magharia",
        "El Mouradia",
        "Haraoua",
        "Hussein Dey",
        "Hydra",
        "Khracia",
        "Kouba",
        "Les Eucalyptus",
        "Mahelma",
        "Marsa",
        "Mohammadia",
        "Oued Koriche",
        "Oued Smar",
        "Ouled Chebel",
        "Ouled Fayet",
        "Rahmania",
        "Rais Hamidou",
        "Reghaia",
        "Rouiba",
        "Saoula",
        "Sidi Mhamed",
        "Sidi Moussa",
        "Souidania",
        "Staoueli",
        "Tassala El Merdja",
        "Zeralda"
    ],
    "Djelfa": [
        "Ain Chouhada",
        "Ain El Ibel",
        "Ain Maabed",
        "Amourah",
        "Beni Yacoub",
        "Charef",
        "Dar Chouikh",
        "Deldoul",
        "Djelfa",
        "Douis",
        "El Guedid",
        "El Idrissia",
        "Feidh El Botma",
        "Guettara",
        "Hassi Bahbah",
        "Hassi El Euch",
        "M'Liliha",
        "Moudjebara",
        "Oum Laadham",
        "Selmana",
        "Sidi Baizid",
        "Tadmit",
        "Zaafrane",
        "Zaccar"
    ],
    "Jijel": [
        "Bordj T'her",
        "Boudria Beni Yadjis",
        "Bouraoui Belhadef",
        "Boussif Ouled Askeur",
        "Chahna",
        "Chekfa",
        "Djemaa Beni Habibi",
        "Djmila",
        "El Ancer",
        "El Aouana",
        "El Kennar Nouchfi",
        "El Milia",
        "Emir Abdelkader",
        "Erraguene",
        "Ghebala",
        "Jijel",
        "Kaous",
        "Kemir Oued Adjoul",
        "Ouadjana",
        "Ouled Rabah",
        "Ouled Yahia Khadrouch",
        "Selma Benziada",
        "Settara",
        "Sidi Abdelaziz",
        "Sidi Maarouf",
        "Taher",
        "Texena",
        "Ziamma Mansouriah"
    ],
    "Se9tif": [
        "Ain Abessa",
        "Ain Arnat",
        "Ain Azal",
        "Ain El Kebira",
        "Ain Lahdjar",
        "Ain Legraj",
        "Ain Oulmane",
        "Ain Roua",
        "Ain Sebt",
        "Ait Naoual Mezada",
        "Ait Tizi",
        "Amoucha",
        "Babor",
        "Bazer Sakhra",
        "Beidha Bordj",
        "Belaa",
        "Beni Aziz",
        "Beni Chebana",
        "Beni Fouda",
        "Beni Hocine",
        "Beni Mouhli",
        "Beni Ouartilane",
        "Bir El Arch",
        "Bir Haddada",
        "Bouandas",
        "Bougaa",
        "Bousselam",
        "Boutaleb",
        "Dehamcha",
        "Djemila",
        "Draa Kebila",
        "El Eulma",
        "El Ouldja",
        "El Ouricia",
        "Guellal",
        "Guelta Zerka",
        "Guenzet",
        "Guidjel",
        "Hamma",
        "Hammam Essokhna",
        "Hammam Guergour",
        "Harbil",
        "Ksar El Abtal",
        "Maaouia",
        "Maouklane",
        "Mezloug",
        "Oued El Barad",
        "Ouled Addouane",
        "Ouled Sabor",
        "Ouled Sidi Ahmed",
        "Ouled Tebben",
        "Rosfa",
        "Salah Bey",
        "Serdj El Ghoul",
        "Setif",
        "Tachouda",
        "Talaifacene",
        "Taya",
        "Tella",
        "Tizi Nbechar"
    ],
    "Saefda": [
        "Ain El Hadjar",
        "Ain Sekhouna",
        "Ain Soltane",
        "Doui Thabet",
        "El Hassasna",
        "Hounet",
        "Maamora",
        "Moulay Larbi",
        "Ouled Brahim",
        "Ouled Khaled",
        "Saida",
        "Sidi Ahmed",
        "Sidi Amar",
        "Sidi Boubekeur",
        "Tircine",
        "Youb"
    ],
    "Skikda": [
        "Ain Bouziane",
        "Ain Cherchar",
        "Ain Kechra",
        "Ain Zouit",
        "Azzaba",
        "Bein El Ouiden",
        "Bekkouche Lakhdar",
        "Ben Azzouz",
        "Beni Bachir",
        "Beni Oulbane",
        "Beni Zid",
        "Bouchtata",
        "Cheraia",
        "Collo",
        "Djendel",
        "El Ghedir",
        "El Hadaik",
        "El Harrouch",
        "El Marsa",
        "Emdjez Edchich",
        "Es Sebt",
        "Filfila",
        "Hamadi Krouma",
        "Kanoua",
        "Kerkera",
        "Kheneg Mayoum",
        "Oued Zehour",
        "Ouldja Boulbalout",
        "Ouled Attia",
        "Ouled Hebaba",
        "Oum Toub",
        "Ramdane Djamel",
        "Salah Bouchaour",
        "Sidi Mezghiche",
        "Skikda",
        "Tamalous",
        "Zerdazas",
        "Zitouna"
    ],
    "Sidi Bel Abbes": [
        "Ain Adden",
        "Ain El Berd",
        "Ain Kada",
        "Ain Thrid",
        "Ain Tindamine",
        "Amarnas",
        "Badredine El Mokrani",
        "Belarbi",
        "Ben Badis",
        "Benachiba Chelia",
        "Bir El Hammam",
        "Boudjebaa El Bordj",
        "Boukhanafis",
        "Chetouane Belaila",
        "Dhaya",
        "El Hacaiba",
        "Hassi Dahou",
        "Hassi Zehana",
        "Lamtar",
        "Makedra",
        "Marhoum",
        "Mcid",
        "Merine",
        "Mezaourou",
        "Mostefa Ben Brahim",
        "Moulay Slissen",
        "Oued Sbaa",
        "Oued Sefioun",
        "Oued Taourira",
        "Ras El Ma",
        "Redjem Demouche",
        "Sehala Thaoura",
        "Sfissef",
        "Sidi Ali Benyoub",
        "Sidi Ali Boussidi",
        "Sidi Bel Abbes",
        "Sidi Brahim",
        "Sidi Chaib",
        "Sidi Dahou",
        "Sidi Hamadouche",
        "Sidi Khaled",
        "Sidi Lahcene",
        "Sidi Yacoub",
        "Tabia",
        "Tafissour",
        "Taoudmout",
        "Teghalimet",
        "Telagh",
        "Tenira",
        "Tessala",
        "Tilmouni",
        "Zerouala"
    ],
    "Annaba": [
        "Ain Berda",
        "Annaba",
        "Berrahel",
        "Chetaibi",
        "Cheurfa",
        "El Bouni",
        "El Hadjar",
        "Eulma",
        "Oued El Aneb",
        "Seraidi",
        "Sidi Amer",
        "Treat"
    ],
    "Guelma": [
        "Ain Ben Beida",
        "Ain Larbi",
        "Ain Makhlouf",
        "Ain Reggada",
        "Ain Sandel",
        "Belkhir",
        "Ben Djarah",
        "Beni Mezline",
        "Bordj Sabat",
        "Bou Hachana",
        "Bou Hamdane",
        "Bouati Mahmoud",
        "Bouchegouf",
        "Boumahra Ahmed",
        "Dahouara",
        "Djeballah Khemissi",
        "El Fedjoudj",
        "Guelaat Bou Sbaa",
        "Guelma",
        "Hammam Maskhoutine",
        "Hamman Nbail",
        "Heliopolis",
        "Houari Boumediene",
        "Khezara",
        "Medjez Amar",
        "Medjez Sfa",
        "Nechmaya",
        "Oued Cheham",
        "Oued Fragha",
        "Oued Zenati",
        "Ras El Agba",
        "Roknia",
        "Salaoua Announa",
        "Tamlouka"
    ],
    "Constantine": [
        "Ain Abid",
        "Ain Smara",
        "Beni Hamiden",
        "Constantine",
        "Didouche Mourad",
        "El Khroub",
        "Hamma Bouziane",
        "Ibn Badis",
        "Ibn Ziad",
        "Mesaoud Boudjeriou",
        "Ouled Rahmoune",
        "Zighoud Youcef"
    ],
    "Medea": [
        "Ain Boucif",
        "Ain Ouksir",
        "Aissaouia",
        "Aziz",
        "Baata",
        "Benchicao",
        "Beni Slimane",
        "Berrouaghia",
        "Bir Ben Laabed",
        "Boghar",
        "Bouaiche",
        "Bouaichoune",
        "Bouchrahil",
        "Boughezoul",
        "Bouskene",
        "Chahbounia",
        "Chelalet El Adhaoura",
        "Cheniguel",
        "Derrag",
        "Deux Bassins",
        "Djouab",
        "Draa Essamar",
        "El Azizia",
        "El Guelbelkebir",
        "El Hamdania",
        "El Omaria",
        "El Ouinet",
        "Hannacha",
        "Kef Lakhdar",
        "Khams Djouamaa",
        "Medea",
        "Medjebar",
        "Meftaha",
        "Meghraoua",
        "Mezerena",
        "Mihoub",
        "Ouamri",
        "Oued Harbil",
        "Ouled Antar",
        "Ouled Bouachra",
        "Ouled Brahim",
        "Ouled Deide",
        "Ouled Hellal",
        "Ouled Maaref",
        "Oum El Djalil",
        "Ouzera",
        "Rebaia",
        "Saneg",
        "Sedraia",
        "Seghouane",
        "Si Mahdjoub",
        "Sidi Damed",
        "Sidi Errabia",
        "Sidi Naamane",
        "Sidi Zahar",
        "Sidi Ziane",
        "Souagui",
        "Tablat",
        "Tafraout",
        "Tamesguida",
        "Tizi Mahdi",
        "Tlatet Eddouair",
        "Zoubiria"
    ],
    "Mostaganem": [
        "Abdelmalek Ramdane",
        "Achaacha",
        "Ain Boudinar",
        "Ain Nouissy",
        "Ain Sidi Cherif",
        "Ain Tadles",
        "Bouguirat",
        "El Hassiane",
        "Fornaka",
        "Hadjadj",
        "Hassi Maameche",
        "Khadra",
        "Kheiredine",
        "Mansourah",
        "Mesra",
        "Mezghrane",
        "Mostaganem",
        "Nekmaria",
        "Oued El Kheir",
        "Ouled Boughalem",
        "Ouled Maallah",
        "Safsaf",
        "Sayada",
        "Sidi Ali",
        "Sidi Bellater",
        "Sidi Lakhdar",
        "Sirat",
        "Souaflia",
        "Sour",
        "Stidia",
        "Tazgait",
        "Touahria"
    ],
    "M'Sila": [
        "Ain El Hadjel",
        "Ain El Melh",
        "Ain Errich",
        "Ain Fares",
        "Ain Khadra",
        "Belaiba",
        "Ben Srour",
        "Beni Ilmane",
        "Benzouh",
        "Berhoum",
        "Bir Foda",
        "Bouti Sayah",
        "Chellal",
        "Dehahna",
        "Djebel Messaad",
        "El Hamel",
        "El Houamed",
        "Hammam Dhalaa",
        "Khettouti Sed Djir",
        "Khoubana",
        "M'cif",
        "Maadid",
        "Maarif",
        "Magra",
        "Medjedel",
        "Msila",
        "Mtarfa",
        "Ouanougha",
        "Oued Chair",
        "Ouled Addi Guebala",
        "Ouled Atia",
        "Ouled Derradj",
        "Ouled Madhi",
        "Ouled Mansour",
        "Ouled Sidi Brahim",
        "Ouled Slimane",
        "Oultene",
        "Sidi Aissa",
        "Sidi Ameur",
        "Sidi Hadjeres",
        "Sidi Mhamed",
        "Slim",
        "Souamaa",
        "Tamsa",
        "Tarmount",
        "Zarzour"
    ],
    "Mascara": [
        "Ain Fares",
        "Ain Fekan",
        "Ain Ferah",
        "Ain Frass",
        "Alaimia",
        "Aouf",
        "Benian",
        "Bou Hanifia",
        "Bou Henni",
        "Chorfa",
        "El Bordj",
        "El Gaada",
        "El Ghomri",
        "El Hachem",
        "El Keurt",
        "El Mamounia",
        "El Menaouer",
        "Ferraguig",
        "Froha",
        "Gharrous",
        "Gherdjoum",
        "Ghriss",
        "Guettena",
        "Hacine",
        "Khalouia",
        "Makdha",
        "Maoussa",
        "Mascara",
        "Matemore",
        "Moctadouz",
        "Mohammadia",
        "Nesmot",
        "Oggaz",
        "Oued El Abtal",
        "Oued Taria",
        "Ras Ain Amirouche",
        "Sedjerara",
        "Sehailia",
        "Sidi Abdeldjebar",
        "Sidi Abdelmoumene",
        "Sidi Boussaid",
        "Sidi Kada",
        "Sig",
        "Teghennif",
        "Tizi",
        "Zahana",
        "Zelmata"
    ],
    "Ouargla": [
        "Ain Beida",
        "Balidat Ameur",
        "Benaceur",
        "El Allia",
        "El Borma",
        "El Hadjira",
        "Hassi Ben Abdellah",
        "Hassi Messaoud",
        "Megarine",
        "Mnaguer",
        "Nezla",
        "Ngoussa",
        "Ouargla",
        "Rouissat",
        "Sidi Khouiled",
        "Sidi Slimane",
        "Taibet",
        "Tamacine",
        "Tebesbest",
        "Touggourt",
        "Zaouia El Abidia"
    ],
    "Oran": [
        "Ain Biya",
        "Ain Kerma",
        "Ain Turk",
        "Arzew",
        "Ben Freha",
        "Bethioua",
        "Bir El Djir",
        "Boufatis",
        "Bousfer",
        "Boutlelis",
        "El Ancar",
        "El Braya",
        "El Karma",
        "Es Senia",
        "Gdyel",
        "Hassi Ben Okba",
        "Hassi Bounif",
        "Hassi Mefsoukh",
        "Marsat El Hadjadj",
        "Mers El Kebir",
        "Messerghin",
        "Oran",
        "Oued Tlelat",
        "Sidi Ben Yabka",
        "Sidi Chami",
        "Tafraoui"
    ],
    "El Bayadh": [
        "Ain El Orak",
        "Arbaouat",
        "Boualem",
        "Bougtoub",
        "Boussemghoun",
        "Brezina",
        "Cheguig",
        "Chellala",
        "El Bayadh",
        "El Bnoud",
        "El Kheither",
        "El Mehara",
        "Ghassoul",
        "Kef El Ahmar",
        "Krakda",
        "Rogassa",
        "Sidi Ameur",
        "Sidi Slimane",
        "Sidi Tifour",
        "Stitten",
        "Tousmouline"
    ],
    "Illizi": [
        "Bordj El Haouasse",
        "Bordj Omar Driss",
        "Debdeb",
        "Djanet",
        "Illizi",
        "In Amenas"
    ],
    "Bordj Bou Arreridj": [
        "Ain Taghrout",
        "Ain Tesra",
        "Belimour",
        "Ben Daoud",
        "Bir Kasdali",
        "Bordj Bou Arreridj",
        "Bordj Ghdir",
        "Bordj Zemoura",
        "Colla",
        "Djaafra",
        "El Ach",
        "El Achir",
        "El Anseur",
        "El Hamadia",
        "El Main",
        "El Mhir",
        "Ghilassa",
        "Haraza",
        "Hasnaoua",
        "Khelil",
        "Ksour",
        "Mansoura",
        "Medjana",
        "Ouled Brahem",
        "Ouled Dahmane",
        "Ouled Sidi Brahim",
        "Rabta",
        "Ras El Oued",
        "Sidi Embarek",
        "Tafreg",
        "Taglait",
        "Teniet En Nasr",
        "Tesmart",
        "Tixter"
    ],
    "Boumerdes": [
        "Afir",
        "Ammal",
        "Baghlia",
        "Ben Choud",
        "Beni Amrane",
        "Bordj Menaiel",
        "Boudouaou",
        "Boudouaou El Bahri",
        "Boumerdes",
        "Bouzegza Keddara",
        "Chabet El Ameur",
        "Corso",
        "Dellys",
        "Djinet",
        "El Kharrouba",
        "Hammedi",
        "Isser",
        "Khemis El Khechna",
        "Laghata",
        "Larbatache",
        "Naciria",
        "Ouled Aissa",
        "Ouled Hedadj",
        "Ouled Moussa",
        "Si Mustapha",
        "Sidi Daoud",
        "Souk El Had",
        "Taourga",
        "Thenia",
        "Tidjelabine",
        "Timezrit",
        "Zemmouri"
    ],
    "El Tarf": [
        "Ain El Assel",
        "Ain Kerma",
        "Asfour",
        "Ben Mhidi",
        "Berrihane",
        "Besbes",
        "Bougous",
        "Bouhadjar",
        "Bouteldja",
        "Chebaita Mokhtar",
        "Chefia",
        "Chihani",
        "Drean",
        "Echatt",
        "El Aioun",
        "El Kala",
        "El Tarf",
        "Hammam Beni Salah",
        "Lac Des Oiseaux",
        "Oued Zitoun",
        "Raml Souk",
        "Souarekh",
        "Zerizer",
        "Zitouna"
    ],
    "Tindouf": [
        "Oum El Assel",
        "Tindouf"
    ],
    "Tissemsilt": [
        "Ammari",
        "Beni Chaib",
        "Beni Lahcene",
        "Bordj Bou Naama",
        "Bordj El Emir Abdelkader",
        "Boucaid",
        "Khemisti",
        "Larbaa",
        "Lardjem",
        "Layoune",
        "Lazharia",
        "Maasem",
        "Melaab",
        "Ouled Bessem",
        "Sidi Abed",
        "Sidi Boutouchent",
        "Sidi Lantri",
        "Sidi Slimane",
        "Tamalaht",
        "Theniet El Had",
        "Tissemsilt",
        "Youssoufia"
    ],
    "El Oued": [
        "Bayadha",
        "Beni Guecha",
        "Debila",
        "Djamaa",
        "Douar El Ma",
        "El Mghair",
        "El Ogla",
        "El Oued",
        "Guemar",
        "Hamraia",
        "Hassani Abdelkrim",
        "Hassi Khelifa",
        "Kouinine",
        "Magrane",
        "Mih Ouansa",
        "Mrara",
        "Nakhla",
        "Oued El Alenda",
        "Oum Touyour",
        "Ourmas",
        "Reguiba",
        "Robbah",
        "Sidi Amrane",
        "Sidi Aoun",
        "Sidi Khellil",
        "Still",
        "Taghzout",
        "Taleb Larbi",
        "Tendla",
        "Trifaoui"
    ],
    "Khenchela": [
        "Ain Touila",
        "Babar",
        "Baghai",
        "Bouhmama",
        "Chelia",
        "Cherchar",
        "Djellal",
        "El Hamma",
        "El Mahmal",
        "El Oueldja",
        "Ensigha",
        "Kais",
        "Khenchela",
        "Khirane",
        "Msara",
        "Mtoussa",
        "Ouled Rechache",
        "Remila",
        "Tamza",
        "Taouzianat",
        "Yabous"
    ],
    "Souk Ahras": [
        "Ain Soltane",
        "Ain Zana",
        "Bir Bouhouche",
        "Drea",
        "Haddada",
        "Hanancha",
        "Khedara",
        "Khemissa",
        "Mdaourouche",
        "Mechroha",
        "Merahna",
        "Oued Keberit",
        "Ouled Driss",
        "Ouled Moumen",
        "Oum El Adhaim",
        "Quillen",
        "Ragouba",
        "Safel El Ouiden",
        "Sedrata",
        "Sidi Fredj",
        "Souk Ahras",
        "Taoura",
        "Terraguelt",
        "Tiffech",
        "Zaarouria",
        "Zouabi"
    ],
    "Tipaza": [
        "Aghabal",
        "Ahmer El Ain",
        "Ain Tagourait",
        "Attatba",
        "Beni Milleuk",
        "Bou Haroun",
        "Bou Ismail",
        "Bourkika",
        "Chaiba",
        "Cherchel",
        "Damous",
        "Douaouda",
        "Fouka",
        "Gouraya",
        "Hadjerat Ennous",
        "Hadjout",
        "Khemisti",
        "Kolea",
        "Larhat",
        "Menaceur",
        "Messelmoun",
        "Meurad",
        "Nodor",
        "Sidi Amar",
        "Sidi Ghiles",
        "Sidi Rached",
        "Sidi Semiane",
        "Tipaza"
    ],
    "Mila": [
        "Ahmed Rachedi",
        "Ain Beida Harriche",
        "Ain Mellouk",
        "Ain Tine",
        "Amira Arras",
        "Benyahia Abderrahmane",
        "Bouhatem",
        "Chelghoum Laid",
        "Chigara",
        "Derradji Bousselah",
        "El Mechira",
        "Elayadi Barbes",
        "Ferdjioua",
        "Grarem Gouga",
        "Hamala",
        "Mila",
        "Minar Zarza",
        "Oued Athmenia",
        "Oued Endja",
        "Oued Seguen",
        "Ouled Khalouf",
        "Rouached",
        "Sidi Khelifa",
        "Sidi Merouane",
        "Tadjenanet",
        "Tassadane Haddada",
        "Telerghma",
        "Terrai Bainen",
        "Tessala Lamatai",
        "Tiberguent",
        "Yahia Beniguecha",
        "Zeghaia"
    ],
    "Ain Defla": [
        "Ain Benian",
        "Ain Bouyahia",
        "Ain Defla",
        "Ain Lechiakh",
        "Ain Soltane",
        "Ain Torki",
        "Arib",
        "Barbouche",
        "Bathia",
        "Belaas",
        "Ben Allal",
        "Bir Ouled Khelifa",
        "Bordj Emir Khaled",
        "Boumedfaa",
        "Bourached",
        "Djelida",
        "Djemaa Ouled Chikh",
        "Djendel",
        "El Abadia",
        "El Amra",
        "El Attaf",
        "El Hassania",
        "El Maine",
        "Hammam Righa",
        "Hoceinia",
        "Khemis Miliana",
        "Mekhatria",
        "Miliana",
        "Oued Chorfa",
        "Oued Djemaa",
        "Rouina",
        "Sidi Lakhdar",
        "Tachta Zegagha",
        "Tarik Ibn Ziad",
        "Tiberkanine",
        "Zeddine"
    ],
    "Naama": [
        "Ain Ben Khelil",
        "Ain Sefra",
        "Assela",
        "Djeniane Bourzeg",
        "El Biod",
        "Kasdir",
        "Makman Ben Amer",
        "Mechria",
        "Moghrar",
        "Naama",
        "Sfissifa",
        "Tiout"
    ],
    "Ain Temouchent": [
        "Aghlal",
        "Ain El Arbaa",
        "Ain Kihal",
        "Ain Temouchent",
        "Ain Tolba",
        "Aoubellil",
        "Beni Saf",
        "Bou Zedjar",
        "Chaabet El Ham",
        "Chentouf",
        "El Amria",
        "El Emir Abdelkader",
        "El Malah",
        "El Messaid",
        "Hammam Bouhadjar",
        "Hassasna",
        "Hassi El Ghella",
        "Oued Berkeche",
        "Oued Sabah",
        "Ouled Boudjemaa",
        "Ouled Kihal",
        "Oulhaca El Gheraba",
        "Sidi Ben Adda",
        "Sidi Boumediene",
        "Sidi Ouriache",
        "Sidi Safi",
        "Tamzoura",
        "Terga"
    ],
    "Ghardaefa": [
        "Berriane",
        "Bounoura",
        "Dhayet Bendhahoua",
        "El Atteuf",
        "El Guerrara",
        "El Meniaa",
        "Ghardaia",
        "Hassi Fehal",
        "Hassi Gara",
        "Mansoura",
        "Metlili",
        "Sebseb",
        "Zelfana"
    ],
    "Relizane": [
        "Ain Rahma",
        "Ain Tarek",
        "Ammi Moussa",
        "Belaassel Bouzegza",
        "Bendaoud",
        "Beni Dergoun",
        "Beni Zentis",
        "Dar Ben Abdellah",
        "Djidiouia",
        "El Guettar",
        "El Hamadna",
        "El Hassi",
        "El Matmar",
        "El Ouldja",
        "Had Echkalla",
        "Hamri",
        "Kalaa",
        "Lahlef",
        "Mazouna",
        "Mediouna",
        "Mendes",
        "Merdja Sidi Abed",
        "Ouarizane",
        "Oued El Djemaa",
        "Oued Essalem",
        "Oued Rhiou",
        "Ouled Aiche",
        "Ouled Sidi Mihoub",
        "Ramka",
        "Relizane",
        "Sidi Khettab",
        "Sidi Lazreg",
        "Sidi Mhamed Ben Ali",
        "Sidi Mhamed Ben Aouda",
        "Sidi Saada",
        "Souk El Haad",
        "Yellel",
        "Zemmoura"
    ],
    "El M'ghair": [],
    "El Menia": [],
    "Ouled Djellal": [],
    "Bordj Baji Mokhtar": [],
    "Béni Abbès": [],
    "Timimoun": [],
    "Touggourt": [],
    "Djanet": [],
    "In Salah": [],
    "In Guezzam": [],
    "Aflou": [
        "Aflou"
    ],
    "El Abiodh Sidi Cheikh": [
        "El Abiodh Sidi Cheikh"
    ],
    "El Aricha": [
        "El Aricha",
        "El Bouihi",
        "El Gor",
        "Sidi Djillali"
    ],
    "El Kantara": [
        "Ain Zaatout",
        "Branis",
        "Djemorah",
        "El Kantara",
        "El Outaya"
    ],
    "Barika": [
        "Barika",
        "Bitam",
        "Djezzar",
        "M'doukel",
        "Metkaouak",
        "Ouled Ammar",
        "Seggana",
        "Tilatou"
    ],
    "Bou Saada": [
        "Bou Saada"
    ],
    "Bir El Ater": [
        "Bir El Ater",
        "Ferkane",
        "Negrine"
    ],
    "Ksar El Boukhari": [
        "Ksar El Boukhari"
    ],
    "Ksar Chellala": [
        "Bougara",
        "Hamadia",
        "Ksar Chellala",
        "Rechaiga",
        "Serghine",
        "Zmalet El Emir Aek"
    ],
    "Ain Oussara": [
        "Ain Fekka",
        "Ain Oussera",
        "Benhar",
        "Birine",
        "Bouira Lahdeb",
        "El Khemis",
        "Guernini",
        "Had Sahary",
        "Hassi Fedoul",
        "Sidi Ladjel"
    ],
    "Messaad": [
        "Messaad",
        "Sed Rahal"
    ]
};